/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
//Wednesday 25 March 2015 11:19:20 AM IST 
#include<stdio.h>


int main()
{
	unsigned int sum = 2;
	unsigned int n1 = 1 , n2 = 2 , n3 = 0;
	while( 1 ){
		
		n3 = n1 + n2;
		printf( " %d\n" , n3 );
		if( n3 <= 4000000 && n3 % 2 == 0 )
			sum += n3;
		else if( n3 > 4000000)
			break;
		n1 = n2;
		n2 = n3;
						
	}
	printf( "sum of even-valued terms = %d\n",sum);
	return 0;
}
